### PR TITLE
Similar format

### PR DESCRIPTION
**Pull request by giggsoff**
Seems, that we need to store things in the same format #53

### CODE REVIEW

**Review by deitch — APPROVED** [review]
LGTM.

**Comment by deitch** [comment]
Fixes #53

**Comment by deitch** [comment]
You ready on this @giggsoff ?

**Comment by giggsoff** [comment]
Actually, it contains your commit from #52. Otherwise everything is fine.

**Comment by deitch** [comment]
I consider that to be a good thing. :-)

**Pull request merged**
