### PR TITLE
basic infrastructure for serving Web files

### PR DESCRIPTION
**Pull request by deitch**
In preparation for having an embedded Web UI, this PR sets up Adam to serve up static Web files. There is a doc describing it, as well as updated README.md

Some important points:

* the static files are under `./web/static`. **Everything** under there is served as static content, as is.
* the static files are compiled right into Adam, enabling the `adam` binary to be completely self-contained. 
* you can override it, e.g. for rapid development purposes, and serve files from the local filesystem with the `--web-dir <directory>` option
* this uses `//go:embed`, so it requires go 1.16+ to build.
* I had to move the `api.probe` call from `/` to `/probe`. I do not know what, if anything, depends upon that, I suspect something from Eden, it was in PR #7 from @giggsoff . I especially need your insight into this.

Other than that, ready to go.

### CODE REVIEW

**Comment by giggsoff** [comment]
Actually inside https://github.com/lf-edge/adam/pull/7#issue-384810104 I implemented endpoint for probe of EVE. It is just 200 response on `/`, so, you can remove `/probe` endpoint if you have new one serving on `/`.

**Comment by deitch** [comment]
That's good to know. Does the content matter? Or does it just look at the response code?

**Comment by giggsoff** [comment]
As I can see in [comment](https://github.com/lf-edge/eve/blob/5176dda2a1adafef6f102517dfc2448f4e463aa2/pkg/pillar/cmd/zedrouter/probe.go#L410-L411) it is just StatusCode check.

**Comment by deitch** [comment]
Then we are good with that. CI is clean, so let's move this in. We always can update it.

**Comment by deitch** [comment]
@rvs this needs your +1 to merge

**Review by rvs — APPROVED** [review]
LGTM. Quick question to both of you @giggsoff @deitch -- now that we have `--web-dir <directory>` can we use that instead of eserver for Eden purposes? I'd love to get rid of one extra moving part on that side.

**Comment by deitch** [comment]
I am concerned it might have different purposes. Adam's `--web-dir` is meant for the Web UI. it doesn't care much - it will serve anything - but at some point that will conflict.

Can we list everything eserver does and we can find a way to get it in?

**Comment by deitch** [comment]
So we just need an ability to serve local files? 

web-dir would do that, but then it couldn't serve up the management website (which now is just an almost empty html page, but will eventually include what you proposed in our discussions).

Is there anything about eserver requiring it to be on 443 and https? If not, I'm perfectly happy to add in another option to serve up another path on another port (likely 80). That only would be enabled by a flag, but that way the two wouldn't interfere.

**Comment by deitch** [comment]
> http and sftp on the same port

How? As soon as I make a tcp connection, the application (L7) protocol for the two are significantly different. Not salient to this conversation, but you have piqued my interest.

> Also it has API to tell what file to put onto eserver

So it doesn't just serve up whatever file is in some local path, but actually is configured via a REST (or similar) API to tell it what paths to serve, and what not to serve?

>  (local file or remote link)

It can serve a local file or reverse-proxy for some remote file over http?

> check the status of file (loading process or size and sha for loaded)

I don't understand the loading part. If it is a local file, then it is there (by definition). If it is remote, isn't it just acting as a reverse proxy?

**Comment by deitch** [comment]
It seems pretty clear that eserver is its own piece of infrastructure and behaviour. Let's leave it alone for now. We can have a real conversation as to whether that full set of capabilities should be embedded into an OSS controller, but let's have that separately and then decide.

**Pull request merged**
