### PR TITLE
redis timeout and retries expand and more verbosity in logs

### PR DESCRIPTION
**Pull request by giggsoff**
In order to stabilize long-running scenarios #95 we can expand timeouts and add retry to our redis client

Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

### CODE REVIEW

**Review by mydatascience — APPROVED** [review]

**Comment by mydatascience** [comment]
@rvs  @deitch  please have a look. This is a critical thing for OSS

**Review by deitch — APPROVED** [review]
This looks fine to me. I think that we should have some way to make the `ioTimeout` configurable rather than hard-coded, but that can wait until a later PR, if you prefer.

**Comment by deitch** [comment]
Is this ready to merge?

**Comment by giggsoff** [comment]
> Is this ready to merge?

Yes, it is ready

**Comment by rvs** [comment]
LGTM

**Pull request merged**
