### PR TITLE
EVE api sync

### PR DESCRIPTION
**Pull request by giggsoff**
Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

### CODE REVIEW

**Comment by deitch** [comment]
@giggsoff thanks for putting this through. I am glad to get us up to a much more up to date version of the API.

Did you actually test all of the code paths? If the API has changed fundamentally, then most of what goes on in [apiHandler.go](https://github.com/lf-edge/adam/blob/master/pkg/server/apiHandler.go) will require reworking. 

Is that file ready to go with the newer version?

**Comment by giggsoff** [comment]
@deitch are you mean API V2? As far as I can see, EVE is still backward compatible with API V1. Registration with the new version from this commit is at least successful for me. This update is needed to work with Mountpoints in applications.
However, there are problems with the first reboot of EVE, but as I understand it is not related to these changes.

**Comment by deitch** [comment]
In that case, lgtm

**Comment by deitch** [comment]
@rvs comments?

**Comment by rvs** [comment]
LGTM

**Pull request merged**
