### PR TITLE
move to jsonpb

### PR DESCRIPTION
**Pull request by giggsoff**
Hi, @rvs 
Unfortunately, using `msgpack` to encode and decode `info.ZInfoMsg` leads to errors like https://gist.github.com/giggsoff/24f6b165ae99dabcdecf45e1df7f23fd
in our branch https://github.com/itmo-eve/eden/tree/redisLoader-rebase . The same time, `logs.LogBundle` parsing works fine.
So, I suggest to use `jsonpb` Marshaller for logs, info and metrics according to this PR.
I successfully build it and test from my own docker registry in branch https://github.com/itmo-eve/eden/tree/jsonpb.

Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

### CODE REVIEW

**Comment by deitch** [comment]
Yeah, we use jsonpb elsewhere as well. This makes sense.

**Comment by rvs** [comment]
The only issue I have against jasonpb is that you can't do json parsing on the Redis end with it (but that's minor -- since we're not using that functionality for now anyway). A bigger question I have for @giggsoff is why do you see the error to begin with? Can you show us a chunk of code that fails on your end?

**Comment by giggsoff** [comment]
@rvs you can see the same problem by running sample app with marshal and unmarshal of ZInfoMsg:
https://gist.github.com/giggsoff/70346838d4623b4983f98768df688e26

**Comment by rvs** [comment]
Ok, got it @giggsoff -- there seems to be a problem indeed. I'm not against us using jsonpb for now but I would like to ask you to please follow up with upstream github.com/vmihailenco/msgpack guys and see if there's any way we can still use msgpack for our use case. At least lets make sure to file an issue and explain the problem statement like you did above.

**Comment by giggsoff** [comment]
@rvs 
I try to do same things with json (not jsonpb) [here](https://gist.github.com/giggsoff/cc87c73a767e047f734410963152a439).
With comment in [line 19](https://gist.github.com/giggsoff/cc87c73a767e047f734410963152a439#file-msgpack-L19) I receive
`json: cannot unmarshal object into Go struct field ZInfoMsg.InfoContent of type info.isZInfoMsg_InfoContent`
So, it cannot unmarshal into non-initialized field with interface{} type.

Without comment in line [line 19](https://gist.github.com/giggsoff/cc87c73a767e047f734410963152a439#file-msgpack-L19) you can see wrong output:
```
2020/05/20 21:55:15 &{AppName:"test"}
2020/05/20 21:55:15 {"InfoContent":{"Ainfo":{"AppName":"test"}}}
2020/05/20 21:55:15 &{cpuArch:"amd64"}
```
against expected the same first and third lines.  
As I understand it, the problem is the presence of an interface and in an attempt to convert json fields to fields available in the implementation of the interface.

**Comment by rvs** [comment]
Right @giggsoff -- this is very likely. Still, can you please file an Issue for MsgPack and ask them if they have any recommendations for this kind of usecase (serializing/deserializing structures that are generated by protoc and thus may have this weird structure around interfaces).

Please CC me on that issue.

**Pull request merged**
