### PR TITLE
Update to Go 1.16, for Darwin/ARM64

### PR DESCRIPTION
**Pull request by vmlemon**
Signed-off-by: Tyson Key <tyson.key@gmail.com>

### CODE REVIEW

**Review by deitch — CHANGES_REQUESTED** [review]
Can you make the version alpine based? At least `1.6-alpine`, if not specifically `1.16.3-alpine3.13`. The alpine one is ~100MB in size vs the non-Alpine ~300MB in size.

**Comment by vmlemon** [comment]
> Can you make the version alpine based? At least `1.6-alpine`, if not specifically `1.16.3-alpine3.13`. The alpine one is ~100MB in size vs the non-Alpine ~300MB in size.

Sure, that should be on 1.16.3-alpine3.13, now. Still builds, on my local machine, by the looks of things.

**Comment by vmlemon** [comment]
> Can you make the version alpine based? At least `1.6-alpine`, if not specifically `1.16.3-alpine3.13`. The alpine one is ~100MB in size vs the non-Alpine ~300MB in size.

Sure, that should be on 1.16.3-alpine3.13, now. Still builds, on my local machine, by the looks of things.

**Comment by deitch** [comment]
Yup, I have been building locally using go1.16 since it came out.

**Review by deitch — APPROVED** [review]

**Comment by rvs** [comment]
Seems like it needs to be rebased @vmlemon

**Comment by vmlemon** [comment]
> Seems like it needs to be rebased @vmlemon

Hmm? I get "Already up to date", if I try to do a "git pull", on this repository, into my personal fork, on my "master" branch, as well as my one for prototyping this change.

**Pull request merged**
