### PR TITLE
[WIP] Postgres device_manager

### PR DESCRIPTION
**Pull request by giggsoff**
Postgres device_manager support

Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

### CODE REVIEW

**Review by rvs — COMMENTED** [review]
I am just curious @giggsoff what's the motivation here? IIRC, the reason we did Redis is because of its streaming capabilities -- so that the client can stream info/metri/log updates. Is there something similar in Postgres you're planning to use?

**Comment by giggsoff** [comment]
Actually, there is Listen/Notify machinery, which allows to subscribe to particular type of events.

**Comment by rvs** [comment]
> Actually, there is Listen/Notify machinery

Can you provide some pointers to the PG documentation please?

**Comment by giggsoff** [comment]
Sure, here you are: https://www.postgresql.org/docs/13/sql-notify.html.

**Comment by rvs** [comment]
Right, but that's not the same -- you still need to do an honest query after you get notified, no?

I was hoping you could enable something like https://wiki.postgresql.org/images/a/ad/South_Bay_PG_Meetup_2016-03-08_PipelineDB.pdf

**Comment by giggsoff** [comment]
> Right, but that's not the same -- you still need to do an honest query after you get notified, no?

Yes, Notification has limit on 5000 bytes of payload, so, I put inside id of object (key in table to query) and id of parent (device/application).

> I was hoping you could enable something like https://wiki.postgresql.org/images/a/ad/South_Bay_PG_Meetup_2016-03-08_PipelineDB.pdf

Sorry, I am little confused with it. Seems, that it adds posibility to create dynamically processing views inside DB. But does it helps for external caller to get the stream?

**Comment by rvs** [comment]
> Yes, Notification has limit on 5000 bytes of payload, so, I put inside id of object (key in table to query) and id of parent (device/application).

Yeah -- that's pretty clunky

> Sorry, I am little confused with it. Seems, that it adds posibility to create dynamically processing views inside DB. But does it helps for external caller to get the stream?

My point is -- I don't see a value jumping into Postgres here. I DO see a value of providing a backend that is Postgres based (so you get the benefit of a traditional RDBMs -- after all, Adam IS a web applications and 3-tier webapps are still very much how this is built). However you need some streaming extensions as well. At this point your best options in that space is TimescaleDB.

So... I'd recommend looking at  TimescaleDB and using their classical Postgres APIs for all the RDBMs stuff + their streaming/time series APIs for what we're currently using Redis for. E.g.:

```
$ docker run -d --name timescaledb -p 5432:5432 -e POSTGRES_PASSWORD=password timescale/timescaledb:2.1.0-pg13
$ psql -U postgres -h localhost
Password for user postgres: password
psql (13.1, server 13.2)
Type "help" for help.

postgres=#
```

Makes sense @giggsoff ?

**Comment by giggsoff** [comment]
Using time series can really be useful in this case. Moreover, I noticed that at the moment I do not include timestamps at all, which is incorrect.
However, I couldn't find anything about streaming in the manual of [TimescaleDB](https://docs.timescale.com/latest/api).

**Comment by rvs** [comment]
> However, I couldn't find anything about streaming in the manual of TimescaleDB.

Perhaps we need to have a proper design discussion then. But basically this is what you need https://blog.timescale.com/blog/timescaledb-1-7-fast-continuous-aggregates-with-real-time-views-postgresql-12-support-and-more-community-features/ @giggsoff

**Comment by giggsoff** [comment]
Let's close this for now and look on another back-ends if we will decide.

**Pull request closed without merging**
