### PR TITLE
Implement POST method handler for /config endpoint

### PR DESCRIPTION
**Pull request by giggsoff**
Due to the impossibility of connecting new versions of EVE to the Adam, the POST method handler for endpoint /config is implemented.
The version of the github.com/lf-edge/eve/api/go package has also been updated. The old version did not allow the deviceIoList array to be configured correctly.

### CODE REVIEW

**Comment by giggsoff** [comment]
Also implemented hash checking between configRequest and current hash

**Comment by deitch** [comment]
Is this a duplicate of #4?

**Comment by rvs** [comment]
Hey @giggsoff can you please check that the current Adam implementation does what you need it to do?

**Comment by giggsoff** [comment]
Hi @rvs 
I apologize for the long silence, the problem was quite hidden.
In my code, I send StatusOK and do not send ConfigResponse buffer if ConfigHash not modified ([here](https://github.com/lf-edge/adam/blob/1a47d7d64abe4bb5cbbced8f516e268fc2ecd5fe/pkg/server/apiHandler.go#L127)). But in EVE I faced with problems in lines of [diag.tryPostUUID](https://github.com/lf-edge/eve/blob/67bc06062115b8fff513d0261ea3808e93c2f49e/pkg/pillar/cmd/diag/diag.go#L821) with trying to parse empty response. In code of [parsePrint](https://github.com/lf-edge/eve/blob/67bc06062115b8fff513d0261ea3808e93c2f49e/pkg/pillar/cmd/diag/diag.go#L841) I found, that I can use StatusNotModified in Adam, but it cannot go through switch in [SendOnIntf](https://github.com/lf-edge/eve/blob/67bc06062115b8fff513d0261ea3808e93c2f49e/pkg/pillar/zedcloud/send.go#L439).
Also I see in my logs from EVE<->Zedcontrol, that for now Zedcontrol return full ConfigResponse:
`2020-02-27T10:54:27.475189+00:00 linuxkit-525400123456 pillar.out {"file":"/pillar/cmd/diag/diag.go:857","func":"github.com/lf-edge/eve/pkg/pillar/cmd/diag.parsePrint","level":"info","msg":"Same ConfigHash","pid":1471,"source":"diag","time":"2020-02-27T10:54:20.32269018Z"}
2020-02-27T10:54:27.511598+00:00 linuxkit-525400123456 pillar.out 
{"file":"/pillar/cmd/diag/diag.go:860","func":"github.com/lf-edge/eve/pkg/pillar/cmd/diag.parsePrint","level":"info","msg":"XXX len 66 hash 80D45798BA06A6BB63F73DF796C904BD6F3D20A6E6D3016E694B29553F93AA15","pid":1471,"source":"diag","time":"2020-02-27T10:54:20.323495799Z"}`

Can you please recheck logic of EVE<->Zedcontrol for sending ConfigResponse?

**Comment by ravi-zededa** [comment]
@giggsoff EVE expects "StatusNotModified" if ConfigHash is not modified and I would expect the controller to do that.

**Comment by giggsoff** [comment]
New pull request after EVE modification: #6

**Pull request merged**
