### PR TITLE
fix flag in docker-compose

### LINKED ISSUE #101: Incorrect option '--self-cert' in docker-compose.yml
The docker-compose.yml file contains the option "--self-cert". If I issue "docker compose up" I get:

```
robert@arch ~/F/Z/r/r/adam> docker compose up                                                                                         
[+] Running 1/1                                                                                                                       
 ⠿ Container adam-adam-1  Recreated                                                                                              0.2s
Attaching to adam-adam-1                                                                                                              
adam-adam-1  | Error: unknown flag: --self-cert  
...
```

Also adam seems to return exit code 0 in this case which is probably not optimal:

```
...
adam-adam-1  |       --server-key string       path to server key (default "run/adam/server-key.pem")
adam-adam-1  | 
adam-adam-1 exited with code 0
```

Regards,
Robert

### PR DESCRIPTION
**Pull request by deitch**
Fixes #101

### CODE REVIEW

**Comment by deitch** [comment]
I tried to add @giggsoff but you weren't in the list of reviewers? 🤷‍♂️

**Review by giggsoff — APPROVED** [review]
Thanks for fixing this

**Comment by deitch** [comment]
Why isn't @giggsoff an official reviewer? We have to get you on there.

**Review by rvs — APPROVED** [review]
LGTM

**Pull request merged**
