### PR TITLE
multiple archs build

### PR DESCRIPTION
**Pull request by giggsoff**
Seems, that we need to build adam for arm64 as well.

Signed-off-by: Petr Fedchenkov <giggsoff@gmail.com>

### CODE REVIEW

**Review by rvs — APPROVED** [review]
LGTM. Let's see how it works. Merging now.

**Comment by giggsoff** [comment]
It looks as expected: https://hub.docker.com/layers/lfedge/adam/0b72a46462c4e1e7de5acce00cea076feb3f8585/images/sha256-14ca09c2c98a402d42021204be44e20feeadfadfea3310017ccb574249772c71?context=explore

**Comment by rvs** [comment]
yup! nice job @giggsoff !

**Comment by deitch** [comment]
Nicely done, and thanks for taking care of it @giggsoff 

FYI, only somewhat related, I have always wanted the ability to release using the docker actions without rebuilding, just tagging. Unfortunately, it doesn't exist, but I opened an issue with them.

**Pull request merged**
