### PR TITLE
Move from env params to cli params only

### PR DESCRIPTION
**Pull request by europaul**
Adam used to get it's certificates and keys through envs. To unify the UX we switch this mechanism to getting paths to files with certificates and keys through the CLI parameters only.

### CODE REVIEW

**Comment by giggsoff** [comment]
Can you please elaborate why this change required by https://github.com/lf-edge/eden/pull/927#issuecomment-1896425468? Looks like we had 3 options to pass certificates before (path to cert in cli, path to cert in ENV and certificate in ENV), but you remove the last, while still using the first.

**Comment by deitch** [comment]
I am not sure that it is _required_. The structure was confusing, though. You provide a file path to a cert, which by default is inside the database path, but is used even if the database is not on disk (e.g. redis or in memory), and then write to that path. I think @europaul's approach makes his straightforward, and like most certificate-based software: provide paths to certs/keys via CLI, software reads it. No confusion about what is provided in alternate approach. 

It isn't just the env var. If we had `--cert-path` and `--cert-content`, it would be equally confusing.

**Comment by europaul** [comment]
@giggsoff @deitch you are right, this change is not required. It is more of a clean-up like @deitch explained. Also the envs were potentially overwriting files on disk, which I think is not desirable.

**Comment by giggsoff** [comment]
Got it, thank you! Please remove the [line](https://github.com/lf-edge/adam/blob/aad2368d41ed5842d314ede2bd82bab8637300ec/README.md?plain=1#L48) from readme as well.

**Review by deitch — APPROVED** [review]

**Comment by deitch** [comment]
Let us know when you are ready to go with this @europaul . 

Any other comments @giggsoff ?

**Comment by europaul** [comment]
> Let us know when you are ready to go with this @europaul .

We need to merge https://github.com/lf-edge/eden/pull/927# before we can merge it (unless we don't increment the Adam version, so that Eden ends up using the old version by default).

**Comment by deitch** [comment]
> We need to merge https://github.com/lf-edge/eden/pull/927 before we can merge it (unless we don't increment the Adam version, so that Eden ends up using the old version by default).

OK, so we can wait on that. Also want to see if @giggsoff has anything else here

**Review by giggsoff — APPROVED** [review]

**Comment by deitch** [comment]
If @giggsoff approved and I approved and @uncleDecart did it, I see no reason to wait on the merge. :-)

**Pull request merged**
